//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechStore.Models
{
    using System;
    using Microsoft.EntityFrameworkCore;
    
    public partial class DBTechStoreEntities : DbContext
    {
        public DBTechStoreEntities(DbContextOptions<DBTechStoreEntities> options) 
    : base(options)
    {
    }
    
        
    
        public virtual DbSet<AdminUsers> AdminUsers { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<LoveProducts> LoveProducts { get; set; }
        public virtual DbSet<OrderDetails> OrderDetails { get; set; }
        public virtual DbSet<OrderPro> OrderPro { get; set; }
        public virtual DbSet<ShippingProviders> ShippingProviders { get; set; }

        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Review> Reviews { get; set; }
        public virtual DbSet<CartItem> CartItems { get; set; }
        public virtual DbSet<Inventory> Inventories { get; set; }
        public virtual DbSet<VIPCustomer> VIPCustomers { get; set; }

        public virtual DbSet<OTPModel> OTPModels { get; set; }
 
        public virtual DbSet<SupportRequest> SupportRequests { get; set; }
        public virtual DbSet<UsedPromotion> UsedPromotions { get; set; }

        
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Entity<UsedPromotion>()
        .HasKey(up => new { up.PromotionID, up.IDCus });

            // 2. Cấu hình Khóa ngoại trỏ về bảng Promotion
            modelBuilder.Entity<UsedPromotion>()
                .HasOne(up => up.Promotion)
                .WithMany(p => p.UsedPromotions) // Đảm bảo bảng Promotion có ICollection<UsedPromotion>
                .HasForeignKey(up => up.PromotionID);

            // 3. Cấu hình Khóa ngoại trỏ về bảng Customer
            modelBuilder.Entity<UsedPromotion>()
                .HasOne(up => up.Customer)
                .WithMany(c => c.UsedPromotions) // Đảm bảo bảng Customer có ICollection<UsedPromotion>
                .HasForeignKey(up => up.IDCus);
            
            modelBuilder.Entity<Products>()
                .HasOne(p => p.Category1) 
                .WithMany(c => c.Products) 
                .HasForeignKey(p => p.Category) 
                .HasPrincipalKey(c => c.IDCate); 
                
            modelBuilder.Entity<ChatMessage>()
                .HasOne(c => c.Customer)
                .WithMany() 
                .HasForeignKey(c => c.IDCus)
                .OnDelete(DeleteBehavior.SetNull);

            // 3. Sử dụng đúng class AdminUsers (CÓ CHỮ S) để tạo khóa ngoại
            modelBuilder.Entity<ChatMessage>()
                .HasOne(a => a.AdminUser)
                .WithMany()
                .HasForeignKey(a => a.AdminID)
                .OnDelete(DeleteBehavior.SetNull);
                
            // 4. Báo cho hệ thống biết class AdminUsers sẽ map với bảng tên "AdminUser" trong SQL
            modelBuilder.Entity<AdminUsers>()
                .ToTable("AdminUsers"); 

            // Cấu hình báo cho EF Core biết bảng OrderPro đang chứa Trigger
            // modelBuilder.Entity<OrderPro>()
            //     .ToTable("OrderPro",tb => tb.HasTrigger("trg_AutoUpgradeVIP"));
                modelBuilder.Entity<OrderPro>()
                .ToTable(tb => tb.UseSqlOutputClause(false));
                modelBuilder.Entity<Promotion>().ToTable(tb => tb.UseSqlOutputClause(false));

            }
    }
}
